const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/envelopes",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Envelopes",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {},
    definitions: {
        Envelopes: {
            id: "integer",
            title: "string",
            budget: "integer"
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/envelopes.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})